[versions]
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"

[libraries]
# Dépendance pour l'API de KSP
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

[plugins]
# Déclaration des plugins Gradle que nous allons utiliser
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }